# Generated by Django 5.1.4 on 2026-08-27 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField()),
                ('seats_taken', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='session_capacity_positive'), models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='session_duration_positive'), models.CheckConstraint(condition=models.Q(('seats_taken__lte', models.F('capacity'))), name='session_seats_within_capacity')],
            },
        ),
    ]
