# Generated by Django 5.1.4 on 2026-08-28 09:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['is_public', 'start_at'], name='session_public_start_idx'),
        ),
    ]
